using System.IO;
using UnityEditor;
using UnityEngine;

namespace PushStars.Editor
{
    /// <summary>
    /// Applies correct TextureImporter settings to Figma PNG exports placed in the UI Sprites folder.
    ///
    /// ── Naming convention ─────────────────────────────────────────────────────────
    ///   btn_*.png          →  9-slice Sprite, border 24 px, Bilinear filter
    ///   chip_*.png         →  9-slice Sprite, border 16 px, Bilinear filter
    ///   badge_*.png        →  9-slice Sprite, border 12 px, Bilinear filter
    ///   icon_sm_*.png      →  Simple Sprite,  no border,   Bilinear filter (≤64 px)
    ///   icon_*.png         →  Simple Sprite,  no border,   Bilinear filter (128 px)
    ///   bg_*.png           →  Simple Sprite,  no border,   Bilinear filter (full-screen)
    ///   ring_*.png         →  Simple Sprite,  no border,   Bilinear filter (rotating ring)
    ///   (any other name)   →  Simple Sprite,  no border,   Bilinear filter
    ///
    /// Files generated by SpriteFactory (pill_*, circle_*, dashed_*, card_*) are skipped —
    /// they already have correct settings applied by that tool.
    ///
    /// ── Workflow ──────────────────────────────────────────────────────────────────
    ///   1. Export PNG from Figma using the agreed sizes / names.
    ///   2. Drop it into  Assets/_Project/UI/Sprites/
    ///   3. Run  Tools → Push Stars → Configure Figma Sprites
    ///   4. Run  Tools → Push Stars → Setup UI Gallery  (prefabs get the new sprite)
    ///   5. Run  Tools → Push Stars → Build Demo Screens  (scenes rebuild)
    ///
    /// Menu: Tools → Push Stars → Configure Figma Sprites
    /// </summary>
    public static class SpriteImporter
    {
        private static readonly string[] SkipPrefixes =
            { "pill_", "circle_", "dashed_", "card_" };

        [MenuItem("Tools/Push Stars/Configure Figma Sprites", priority = 203)]
        public static void ConfigureAll()
        {
            string dir   = SpriteFactory.SpritesDir;
            var    guids = AssetDatabase.FindAssets("t:Texture2D", new[] { dir });
            int    count = 0;

            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string file = Path.GetFileNameWithoutExtension(path).ToLowerInvariant();

                if (IsGeneratedByFactory(file)) continue;

                ApplySettings(path, file);
                count++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"[SpriteImporter] ✓ Configured {count} Figma sprite(s). " +
                      "Re-run  Tools → Push Stars → Setup UI Gallery  to update prefabs.");
        }

        /// <summary>Configures a single PNG at <paramref name="assetPath"/>.</summary>
        public static void ConfigureSingle(string assetPath)
        {
            string file = Path.GetFileNameWithoutExtension(assetPath).ToLowerInvariant();
            if (IsGeneratedByFactory(file)) return;
            ApplySettings(assetPath, file);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        static bool IsGeneratedByFactory(string filename)
        {
            foreach (var prefix in SkipPrefixes)
                if (filename.StartsWith(prefix)) return true;
            return false;
        }

        static void ApplySettings(string path, string name)
        {
            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer == null) return;

            importer.textureType         = TextureImporterType.Sprite;
            importer.spriteImportMode    = SpriteImportMode.Single;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled       = false;
            importer.wrapMode            = TextureWrapMode.Clamp;

            var settings = new TextureImporterSettings();
            importer.ReadTextureSettings(settings);
            settings.spriteMeshType                     = SpriteMeshType.FullRect;
            settings.spriteGenerateFallbackPhysicsShape = false;

            // Determine filter + border from naming prefix.
            // btn_ sprites that contain "_nav_" or "_vs_" are circular icons, not pills — no 9-slice.
            bool isBtnIcon = name.StartsWith("btn_") &&
                             (name.Contains("_nav_") || name.Contains("_vs_"));

            if (name.StartsWith("btn_") && !isBtnIcon)
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(24, 24, 24, 24);
            }
            else if (name.StartsWith("chip_"))
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(16, 16, 16, 16);
            }
            else if (name.StartsWith("badge_"))
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(12, 12, 12, 12);
            }
            else if (name == "mode" || name == "type" ||
                     name.StartsWith("mode_") || name.StartsWith("type_"))
            {
                // Chip-shape sprites (mode.png = gold border, type.png = blue border).
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(20, 20, 20, 20);
            }
            // These bg_* sprites are 9-slice PANELS (not full-screen art) — they need borders,
            // unlike the generic bg_ rule below. Border (left,bottom,right,top), kept < half-size.
            else if (name == "bg_streak_aura")
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(16, 8, 16, 8); // native 66×21 tag
            }
            else if (name == "bg_card")
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(24, 24, 24, 24); // native 251×79 card
            }
            // The bottom-nav plate: a capsule at 2.92:1, far off the nav bar's own 4.79:1, so it
            // has to be 9-sliced (not just stretched, like plashka.png's near-matching aspect gets
            // away with) or the rounded ends pinch into ellipses. The end caps are full semicircles
            // spanning the WHOLE height (native 502×172, radius = height/2 = 86) — every side needs
            // a border ~= that radius, pulled in slightly for blend room, not just left/right.
            // (78,16,78,16) was tried first and left the caps mostly inside the stretchy left/right
            // EDGE tiles instead of the fixed corners — squashing them into a lens/boat shape when
            // the bar renders far shorter than the source art (66 pt tall vs. 172 px native).
            // Square corners fix it: Unity's own oversized-border fallback then shrinks all four
            // sides by the same factor, so the quarter-circle corners stay round, just smaller.
            else if (name == "menu_floor")
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(78, 78, 78, 78);
            }
            else if (name.StartsWith("icon_sm_"))
            {
                // Bilinear — small icons still need smooth scaling on Retina displays.
                // Point filter is only for intentional pixel-art, not UI icons.
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = Vector4.zero;
            }
            else
            {
                // icon_*, bg_*, ring_*, or anything else
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = Vector4.zero;
            }

            importer.SetTextureSettings(settings);

            // Platform overrides — ASTC on iOS, ETC2 on Android.
            // Both are GPU-native compressed formats: look identical to PNG at runtime
            // but take 4-8x less memory and load faster.
            // maxTextureSize: bg images cap at 2048, icons at 512 (enough for 3x Retina).
            bool isBg = name.StartsWith("bg_") || name == "bg";
            int  maxSize = isBg ? 2048 : 512;

            importer.SetPlatformTextureSettings(new TextureImporterPlatformSettings
            {
                name            = "iPhone",
                overridden      = true,
                maxTextureSize  = maxSize,
                format          = TextureImporterFormat.ASTC_6x6,
                compressionQuality = 100,
            });
            importer.SetPlatformTextureSettings(new TextureImporterPlatformSettings
            {
                name            = "Android",
                overridden      = true,
                maxTextureSize  = maxSize,
                format          = TextureImporterFormat.ETC2_RGBA8,
                compressionQuality = 100,
            });

            importer.SaveAndReimport();
            Debug.Log($"[SpriteImporter] Configured: {path}");
        }
    }
}
