using System.IO;
using UnityEditor;
using UnityEngine;

namespace PushStars.Editor
{
    /// <summary>
    /// Applies correct TextureImporter settings to Figma PNG exports placed in the UI Sprites folder.
    ///
    /// ── Naming convention ─────────────────────────────────────────────────────────
    ///   btn_*.png          →  9-slice Sprite, border 24 px, Bilinear filter
    ///   chip_*.png         →  9-slice Sprite, border 16 px, Bilinear filter
    ///   badge_*.png        →  9-slice Sprite, border 12 px, Bilinear filter
    ///   icon_sm_*.png      →  Simple Sprite,  no border,   Bilinear filter (≤64 px)
    ///   icon_*.png         →  Simple Sprite,  no border,   Bilinear filter (128 px)
    ///   bg_*.png, *_bg.png →  Simple Sprite,  no border,   Bilinear filter (full-screen)
    ///   bar_*.png          →  3-slice Sprite, caps only,  @3x export (loading bar)
    ///   onb_*.png          →  Simple Sprite,  no border,   @3x export (onboarding art)
    ///   ring_*.png         →  Simple Sprite,  no border,   Bilinear filter (rotating ring)
    ///   (any other name)   →  Simple Sprite,  no border,   Bilinear filter
    ///
    /// Files generated by SpriteFactory (pill_*, circle_*, dashed_*, card_*) are skipped —
    /// they already have correct settings applied by that tool.
    ///
    /// ── Workflow ──────────────────────────────────────────────────────────────────
    ///   1. Export PNG from Figma using the agreed sizes / names.
    ///   2. Drop it into  Assets/_Project/UI/Sprites/
    ///   3. Run  Tools → Push Stars → Configure Figma Sprites
    ///   4. Run  Tools → Push Stars → Setup UI Gallery  (prefabs get the new sprite)
    ///   5. Run  Tools → Push Stars → Build Demo Screens  (scenes rebuild)
    ///
    /// Menu: Tools → Push Stars → Configure Figma Sprites
    /// </summary>
    public static class SpriteImporter
    {
        private static readonly string[] SkipPrefixes =
            { "pill_", "circle_", "dashed_", "card_" };

        [MenuItem("Tools/Push Stars/Configure Figma Sprites", priority = 203)]
        public static void ConfigureAll()
        {
            string dir   = SpriteFactory.SpritesDir;
            var    guids = AssetDatabase.FindAssets("t:Texture2D", new[] { dir });
            int    count = 0;

            foreach (var guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);
                string file = Path.GetFileNameWithoutExtension(path).ToLowerInvariant();

                if (IsGeneratedByFactory(file)) continue;

                ApplySettings(path, file);
                count++;
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"[SpriteImporter] ✓ Configured {count} Figma sprite(s). " +
                      "Re-run  Tools → Push Stars → Setup UI Gallery  to update prefabs.");
        }

        /// <summary>
        /// Loads a UI sprite, fixing its import settings first if the PNG has only ever been
        /// imported as a plain texture.
        ///
        /// <para>This project is in 3D mode, so a Figma export dropped into the sprites folder
        /// arrives as a Texture. Asking for a Sprite it was never imported as returns null with
        /// nothing to say why — a blank space in a built screen and no error anywhere. Every scene
        /// tool goes through here rather than through AssetDatabase, so dropping a file in and
        /// running a build tool is the whole workflow.</para>
        /// </summary>
        public static Sprite Load(string assetPath)
        {
            var sprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
            if (sprite != null) return sprite;

            if (!File.Exists(assetPath))
            {
                Debug.LogWarning($"[SpriteImporter] Missing sprite: {assetPath}");
                return null;
            }

            ConfigureSingle(assetPath);
            sprite = AssetDatabase.LoadAssetAtPath<Sprite>(assetPath);
            if (sprite == null)
                Debug.LogWarning($"[SpriteImporter] {assetPath} exists but would not load as a Sprite.");
            return sprite;
        }

        /// <summary>Configures a single PNG at <paramref name="assetPath"/>.</summary>
        public static void ConfigureSingle(string assetPath)
        {
            string file = Path.GetFileNameWithoutExtension(assetPath).ToLowerInvariant();
            if (IsGeneratedByFactory(file)) return;
            ApplySettings(assetPath, file);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        // ── Helpers ───────────────────────────────────────────────────────────────

        static bool IsGeneratedByFactory(string filename)
        {
            foreach (var prefix in SkipPrefixes)
                if (filename.StartsWith(prefix)) return true;
            return false;
        }

        /// <summary>Pixel height straight out of the PNG's header. The imported texture cannot be
        /// asked: an earlier pass may already have clamped it to a maxTextureSize, and a border
        /// measured against a clamped height is wrong for the source it is stored against.</summary>
        static int PngHeight(string path)
        {
            using var fs = File.OpenRead(path);
            var head = new byte[24];
            if (fs.Read(head, 0, 24) < 24) return 0;
            // IHDR: width at byte 16, height at byte 20, both big-endian.
            return (head[20] << 24) | (head[21] << 16) | (head[22] << 8) | head[23];
        }

        static void ApplySettings(string path, string name)
        {
            var importer = AssetImporter.GetAtPath(path) as TextureImporter;
            if (importer == null) return;

            importer.textureType         = TextureImporterType.Sprite;
            importer.spriteImportMode    = SpriteImportMode.Single;
            importer.alphaIsTransparency = true;
            importer.mipmapEnabled       = false;
            importer.wrapMode            = TextureWrapMode.Clamp;

            var settings = new TextureImporterSettings();
            importer.ReadTextureSettings(settings);
            settings.spriteMeshType                     = SpriteMeshType.FullRect;
            settings.spriteGenerateFallbackPhysicsShape = false;

            // Determine filter + border from naming prefix.
            // btn_ sprites that contain "_nav_" or "_vs_" are circular icons, not pills — no 9-slice.
            bool isBtnIcon = name.StartsWith("btn_") &&
                             (name.Contains("_nav_") || name.Contains("_vs_"));

            if (name.StartsWith("btn_") && !isBtnIcon)
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(24, 24, 24, 24);
            }
            else if (name.StartsWith("chip_"))
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(16, 16, 16, 16);
            }
            else if (name.StartsWith("badge_"))
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(12, 12, 12, 12);
            }
            else if (name == "mode" || name == "type" ||
                     name.StartsWith("mode_") || name.StartsWith("type_"))
            {
                // Chip-shape sprites (mode.png = gold border, type.png = blue border).
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(20, 20, 20, 20);
            }
            // These bg_* sprites are 9-slice PANELS (not full-screen art) — they need borders,
            // unlike the generic bg_ rule below. Border (left,bottom,right,top), kept < half-size.
            else if (name == "bg_streak_aura")
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(16, 8, 16, 8); // native 66×21 tag
            }
            else if (name == "bg_card")
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = new Vector4(24, 24, 24, 24); // native 251×79 card
            }
            // The bottom-nav plate: finished art at its own 2.92:1, not a stretchable panel — two
            // rounds of 9-slice border tuning (pinched caps, then a lens/boat warp) both came from
            // forcing it into the bar's unrelated 4.79:1 rect. MainVsScreenSetup now displays it
            // Simple + preserveAspect at its native size instead, so no border is needed at all —
            // left at zero rather than deleting the case, so filter/compression still get set.
            else if (name == "menu_floor")
            {
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = Vector4.zero;
            }
            // The loading bar's own art, once it has been exported rather than generated. It
            // stretches horizontally and never vertically, so only the caps are sliced: a top or
            // bottom border would resample the gradient down its height into one repeated row.
            // The cap is half the source height — the radius a capsule end has by definition — and
            // the sprite is read at 3× because these are @3x exports, which is also what keeps that
            // border at the radius it was drawn with instead of three times it.
            else if (name.StartsWith("bar_"))
            {
                importer.filterMode          = FilterMode.Bilinear;
                importer.spritePixelsPerUnit = 300f;
                float cap = PngHeight(path) * 0.5f;
                settings.spriteBorder = new Vector4(cap, 0f, cap, 0f);
            }
            // Onboarding artwork, exported from Figma at @3x. Read back at ppu 300, which is what
            // makes Image.SetNativeSize hand back the size the element has in the comp instead of
            // three times it — the layout can then be written in the design's own numbers. The
            // matching maxTextureSize below has to leave them alone for that to hold: a clamp
            // shrinks the sprite's rect while the ppu stays, and every native size shrinks with it.
            else if (name.StartsWith("onb_"))
            {
                importer.filterMode          = FilterMode.Bilinear;
                importer.spritePixelsPerUnit = 300f;
                settings.spriteBorder        = Vector4.zero;
            }
            else if (name.StartsWith("icon_sm_"))
            {
                // Bilinear — small icons still need smooth scaling on Retina displays.
                // Point filter is only for intentional pixel-art, not UI icons.
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = Vector4.zero;
            }
            else
            {
                // icon_*, bg_*, ring_*, or anything else
                importer.filterMode   = FilterMode.Bilinear;
                settings.spriteBorder = Vector4.zero;
            }

            importer.SetTextureSettings(settings);

            // Platform overrides — ASTC on iOS, ETC2 on Android.
            // Both are GPU-native compressed formats: look identical to PNG at runtime
            // but take 4-8x less memory and load faster.
            // maxTextureSize: bg images cap at 2048, icons at 512 (enough for 3x Retina).
            // Full-screen art is matched at either end of the name: the convention is bg_*, but
            // a Figma export arrives named for its screen first (loading_bg), and capping that at
            // the icon size resamples a whole background down to 512 px.
            bool isBg = name.StartsWith("bg_") || name.EndsWith("_bg") || name == "bg";
            int  maxSize = isBg ? 2048
                         : name.StartsWith("bar_") || name.StartsWith("onb_") ? 1024
                         : 512;

            importer.SetPlatformTextureSettings(new TextureImporterPlatformSettings
            {
                name            = "iPhone",
                overridden      = true,
                maxTextureSize  = maxSize,
                format          = TextureImporterFormat.ASTC_6x6,
                compressionQuality = 100,
            });
            importer.SetPlatformTextureSettings(new TextureImporterPlatformSettings
            {
                name            = "Android",
                overridden      = true,
                maxTextureSize  = maxSize,
                format          = TextureImporterFormat.ETC2_RGBA8,
                compressionQuality = 100,
            });

            importer.SaveAndReimport();
            Debug.Log($"[SpriteImporter] Configured: {path}");
        }
    }
}
