using UnityEngine;

namespace PushStars.UI
{
    /// <summary>
    /// Single source of truth for all visual colour tokens in Push Stars.
    /// Derived from the official design mockups in docs/design/screens/.
    /// Create via: Assets → Create → Push Stars → Theme
    /// The canonical runtime instance lives at:
    ///   Assets/_Project/UI/Theme/Resources/PushStarsTheme.asset
    ///
    /// Sprite slots are auto-populated by UIGallerySetup. Priority:
    ///   1. Real Figma PNG  (btn_primary.png, chip.png, …)
    ///   2. Procedural PNG  (pill_24.png, circle_128.png, …) generated by SpriteFactory
    /// Override any slot manually in the Inspector; Setup won't clear manual refs.
    /// </summary>
    [CreateAssetMenu(fileName = "PushStarsTheme", menuName = "Push Stars/Theme", order = 0)]
    public class PushStarsTheme : ScriptableObject
    {
        // ── Sprite shapes (9-slice where noted; tinted via Image.color at runtime) ──

        [Header("Sprites — buttons / chips (9-slice, white → tinted by Image.color)")]
        /// <summary>Full-width pill for PrimaryButton.
        /// Figma: btn_start.png | btn_primary.png | fallback: pill_24.png</summary>
        public Sprite BtnShape;
        /// <summary>Chip normal state (blue border). Figma: type.png | fallback: pill_16.png</summary>
        public Sprite ChipShape;
        /// <summary>Chip normal state — alias for ChipShape. Figma: type.png</summary>
        public Sprite ChipShapeNormal;
        /// <summary>Chip selected state (gold border). Figma: mode.png</summary>
        public Sprite ChipShapeSelected;
        /// <summary>Small pill for PlayerPill/TrophyRow.
        /// Figma: badge.png | fallback: pill_12.png</summary>
        public Sprite BadgeShape;

        [Header("Sprites — icons / rings")]
        /// <summary>Plain white circle for nav tabs (tinted via Image.color).
        /// Figma: icon_circle.png | fallback: circle_128.png</summary>
        public Sprite CircleShape;
        /// <summary>Pre-coloured VS badge (blue + text baked in, no tinting).
        /// Figma: btn_VS_main_nav_active.png</summary>
        public Sprite VSBadge;
        /// <summary>Dashed rotating ring for matchmaking.
        /// Figma: ring_dashed.png | fallback: dashed_ring_512.png</summary>
        public Sprite RingShape;

        [Header("Sprites — backgrounds")]
        /// <summary>Full-screen background image. Figma: BG.png</summary>
        public Sprite BgImage;
        /// <summary>Decorative bg behind streak+aura top-bar pills. Figma: bg_streak_aura.png</summary>
        public Sprite BgStreakAura;
        /// <summary>Card / panel shape. Figma: bg_card.png (was Rectangle 245)</summary>
        public Sprite BgCard;

        [Header("Sprites — navigation icons (not-active state)")]
        /// <summary>League tab. Figma: btn_Leage_nav_notactive.png</summary>
        public Sprite NavLeague;
        /// <summary>Profile tab. Figma: btn_profile_nav_notactive.png | profile.png</summary>
        public Sprite NavProfile;
        /// <summary>Profile tab — active state (pre-coloured blue badge). Figma: profile_active.png</summary>
        public Sprite NavProfileActive;

        [Header("Sprites — small icons")]
        /// <summary>Aura / currency icon. Figma: aura.png | icon_aura.png</summary>
        public Sprite IconAura;
        /// <summary>Lightning / streak icon. Figma: icon_lightning.png</summary>
        public Sprite IconLightning;
        /// <summary>Lightning decoration for background. Figma: icon_lightning_for_BG.png</summary>
        public Sprite IconLightningBG;
        /// <summary>Pushup / exercise icon. Figma: pushup.png | icon_pushup.png</summary>
        public Sprite IconPushup;
        /// <summary>Timer icon. Figma: time.png | icon_time.png</summary>
        public Sprite IconTime;
        /// <summary>Trophy cup icon. Figma: cup_.png</summary>
        public Sprite IconCup;
        /// <summary>Streak icon. Figma: streak.png</summary>
        public Sprite IconStreak;
        /// <summary>XP / experience lightning. Figma: exp_lightning.png</summary>
        public Sprite IconXP;
        /// <summary>Win result icon. Figma: win.png</summary>
        public Sprite IconWin;
        /// <summary>Lose result icon. Figma: lose.png</summary>
        public Sprite IconLose;
        /// <summary>Up arrow. Figma: up.png</summary>
        public Sprite IconUp;
        /// <summary>Down arrow. Figma: down.png</summary>
        public Sprite IconDown;
        /// <summary>Plus / add icon. Figma: plus.png</summary>
        public Sprite IconPlus;
        /// <summary>Level badge icon. Figma: lvl.png</summary>
        public Sprite IconLevel;
        /// <summary>Statistics icon. Figma: statics.png</summary>
        public Sprite IconStatics;

        [Header("Sprites — button shapes (pre-colored Figma, use Color.white)")]
        /// <summary>Red pill button for ВЫЙТИ. Figma: red_btn.png</summary>
        public Sprite BtnExitShape;
        /// <summary>Green pill button for ГОТОВ. Figma: green_btn.png</summary>
        public Sprite BtnReadyShape;

        [Header("Sprites — VS / search screen")]
        /// <summary>VS badge for search opponent screen. Figma: VS_for_serching.png</summary>
        public Sprite VSBadgeSearch;
        /// <summary>Spinning ring for the finding-opponent animation. Figma: circle_finding_animation.png</summary>
        public Sprite RingFinding;

        // ── Colour tokens ─────────────────────────────────────────────────────────

        [Header("Backgrounds")]
        public Color BgDark        = new Color32( 19,  19,  31, 255); // #13131F — main dark bg
        public Color NavBg         = new Color32( 28,  28,  46, 255); // #1C1C2E — bottom nav pill

        [Header("Primary accent — Blue (main CTAs, active tab, VS badge)")]
        public Color AccentBlue    = new Color32( 45,  91, 227, 255); // #2D5BE3

        [Header("Secondary accents")]
        public Color AccentYellow  = new Color32(245, 200,  66, 255); // #F5C842 — XP, level, rep counter
        public Color AccentLime    = new Color32(107, 255,  74, 255); // #6BFF4A — ПОБЕДА / win score

        [Header("State colours")]
        public Color TrophyGold    = new Color32(245, 200,  66, 255); // #F5C842
        public Color DangerRed     = new Color32(198,  40,  40, 255); // #C62828 — ВЫЙТИ / loss

        [Header("Arena (fight HUD)")]
        public Color ArenaRed      = new Color32(122,  26,  26, 255); // #7A1A1A — opponent half
        public Color ArenaBlue     = new Color32( 26,  54, 128, 255); // #1A3680 — player half

        [Header("Text")]
        public Color TextPrimary   = new Color32(255, 255, 255, 255); // #FFFFFF
        public Color TextSecondary = new Color32(136, 136, 170, 255); // #8888AA

        [Header("Buttons")]
        // Blue  — primary action: НАЙТИ СОПЕРНИКА
        public Color BtnPrimaryBg  = new Color32( 45,  91, 227, 255); // #2D5BE3
        public Color BtnPrimaryFg  = new Color32(255, 255, 255, 255);

        // Green — success/confirm: I'M READY, НА ГЛАВНУЮ, ДАЛЕЕ, FINISH
        public Color BtnSuccessBg  = new Color32( 69, 160,  73, 255); // #459049
        public Color BtnSuccessFg  = new Color32(255, 255, 255, 255);

        // Dark  — mode chips unselected
        public Color BtnSecondaryBg = new Color32( 28,  28,  46, 255); // #1C1C2E
        public Color BtnSecondaryFg = new Color32(255, 255, 255, 255);

        // Red   — destructive: ВЫЙТИ (exit from search)
        public Color BtnDangerBg   = new Color32(198,  40,  40, 255); // #C62828
        public Color BtnDangerFg   = new Color32(255, 255, 255, 255);

        [Header("Chip selected state (yellow outline style)")]
        public Color ChipSelectedBorder = new Color32(245, 200,  66, 255); // #F5C842
        public Color ChipSelectedFg     = new Color32(245, 200,  66, 255);
        public Color ChipNormalFg       = new Color32(200, 200, 220, 255); // #C8C8DC

        [Header("Exit Button (ВЫЙТИ — search opponent screen)")]
        /// <summary>Vivid coral-red neon border stroke. Figma: border on ВЫЙТИ pill.</summary>
        public Color BtnExitBorder = new Color32(255,  60,  90, 255); // #FF3C5A — neon coral
        /// <summary>Dark maroon fill — visible dark red, not near-black.</summary>
        public Color BtnExitFill   = new Color32( 62,  10,  10, 255); // #3E0A0A — dark maroon
        /// <summary>Label colour on the exit button. Figma: #FF021B</summary>
        public Color BtnExitFg     = new Color32(255,   2,  27, 255); // #FF021B — bright red text

        [Header("Ready Button (ГОТОВ — success confirm screen)")]
        /// <summary>Neon lime border — reuses AccentLime (#6BFF4A).</summary>
        public Color BtnReadyBorder = new Color32(107, 255,  74, 255); // #6BFF4A — neon lime (= AccentLime)
        /// <summary>Dark forest-green fill — visible dark green, not near-black.</summary>
        public Color BtnReadyFill   = new Color32( 15,  46,   5, 255); // #0F2E05 — dark forest
        /// <summary>Label colour on the ready button. Figma: #52FF02</summary>
        public Color BtnReadyFg     = new Color32( 82, 255,   2, 255); // #52FF02 — bright lime text
    }
}
