using UnityEngine;

namespace PushStars.UI
{
    /// <summary>
    /// Keeps the character on the menu stage from looking like a looping GIF. He runs his main idle
    /// as usual, and every few loops breaks into a one-shot accent — the arm stretch — before
    /// settling back. Both directions are cross-faded, so the break reads as the same person
    /// shifting rather than as a clip cut.
    ///
    /// <para>Driven from here rather than from transitions inside the AnimatorController on
    /// purpose: the controller is regenerated by the import tool, and every consumer in this
    /// project drives the character by state name. Timing and blend live where they can be tuned
    /// without touching either.</para>
    /// </summary>
    [DisallowMultipleComponent]
    public class CharacterIdleAccent : MonoBehaviour
    {
        [Header("Animator")]
        [SerializeField] private Animator _animator;

        [Tooltip("State the character rests in. Must exist in the controller.")]
        [SerializeField] private string _idleState = "Idle";

        [Tooltip("One-shot state played as the break. Import it with Loop Time OFF.")]
        [SerializeField] private string _accentState = "WarriorIdle";

        [Header("Timing")]
        [Tooltip("How many full idle loops pass between accents.")]
        [SerializeField, Min(1)] private int _loopsBetweenAccents = 3;

        [Tooltip("Cross-fade length, seconds. Long enough to hide the cut, short enough that the " +
                 "stretch still starts on time.")]
        [SerializeField, Range(0f, 1.5f)] private float _blendSeconds = 0.35f;

        [Tooltip("Masked layer the break plays on. Empty, or absent from the controller, falls " +
                 "back to cross-fading it on the base layer — which moves the legs too.")]
        [SerializeField] private string _accentLayerName = "Accent";

        private int _idleHash;
        private int _accentHash;
        private int _loopsSeen;
        private float _lastIdleTime;

        /// <summary>Index of the masked layer, or 0 when the controller has none.</summary>
        private int _accentLayer;
        private float _layerWeight;
        private bool _accenting;

        /// <summary>Loops completed since the last accent — surfaced for tuning and tests.</summary>
        public int LoopsSinceAccent => _loopsSeen;

        private void Awake()
        {
            if (_animator == null) _animator = GetComponentInChildren<Animator>();
            _idleHash   = Animator.StringToHash(_idleState);
            _accentHash = Animator.StringToHash(_accentState);
            _accentLayer = FindAccentLayer();
        }

        private void OnEnable()
        {
            _loopsSeen = 0;
            _lastIdleTime = 0f;
            _accenting = false;
            _layerWeight = 0f;
            if (_accentLayer > 0 && _animator != null) _animator.SetLayerWeight(_accentLayer, 0f);
        }

        /// <summary>The masked layer's index, or 0 when the controller predates it.</summary>
        private int FindAccentLayer()
        {
            if (_animator == null || string.IsNullOrEmpty(_accentLayerName)) return 0;
            if (_animator.runtimeAnimatorController == null) return 0;

            for (int i = 1; i < _animator.layerCount; i++)
                if (_animator.GetLayerName(i) == _accentLayerName) return i;

            return 0;
        }

        /// <summary>Points the accent at an animator and its two states. For models built at
        /// runtime — the body <see cref="CharacterRoster"/> swaps in — where the component is added
        /// to a fresh instance and so has nothing serialized to read. Awake has already run by the
        /// time AddComponent returns, so the hashes are rebuilt here rather than left stale.</summary>
        public void Configure(Animator animator, string idleState, string accentState)
        {
            _animator = animator;
            if (!string.IsNullOrEmpty(idleState))   _idleState   = idleState;
            if (!string.IsNullOrEmpty(accentState)) _accentState = accentState;

            _idleHash   = Animator.StringToHash(_idleState);
            _accentHash = Animator.StringToHash(_accentState);
            _accentLayer = FindAccentLayer();
            _accenting  = false;
            _layerWeight = 0f;
            _loopsSeen  = 0;
            _lastIdleTime = 0f;
        }

        private void Update()
        {
            if (_animator == null || !_animator.isActiveAndEnabled) return;
            if (_animator.runtimeAnimatorController == null) return;

            if (_accentLayer > 0) { UpdateMasked(); return; }
            UpdateFullBody();
        }

        /// <summary>The break on its own masked layer: the base layer keeps running the idle
        /// underneath, so the feet stay where it puts them, and only the layer's weight moves.
        /// Fading a weight is what replaces the cross-fade — there is nothing to blend to, because
        /// the pose being returned to was never left.</summary>
        private void UpdateMasked()
        {
            float step = Time.deltaTime / Mathf.Max(_blendSeconds, 0.01f);

            if (_accenting)
            {
                var accent = _animator.GetCurrentAnimatorStateInfo(_accentLayer);
                bool ending = accent.shortNameHash == _accentHash && Ending(accent);

                _layerWeight = Mathf.MoveTowards(_layerWeight, ending ? 0f : 1f, step);
                _animator.SetLayerWeight(_accentLayer, _layerWeight);

                if (!ending || _layerWeight > 0f) return;

                _accenting = false;
                _loopsSeen = 0;
                _lastIdleTime = 0f;
                return;
            }

            if (!CountIdleLoop()) return;

            _animator.Play(_accentHash, _accentLayer, 0f);
            _accenting = true;
        }

        /// <summary>Counts idle loops on the base layer. False while something other than the idle
        /// owns the body, or until enough loops have passed for the next break.</summary>
        private bool CountIdleLoop()
        {
            if (_animator.IsInTransition(0)) return false;

            var state = _animator.GetCurrentAnimatorStateInfo(0);
            // Anything else owns the body right now (a victory, a duel pose) — stay out of its way.
            if (state.shortNameHash != _idleHash) return false;

            float t = state.normalizedTime % 1f;
            if (t < _lastIdleTime) _loopsSeen++;   // normalizedTime wrapped: one loop done
            _lastIdleTime = t;

            return _loopsSeen >= _loopsBetweenAccents;
        }

        /// <summary>Start the return early enough that the fade covers the break's tail instead of
        /// holding its last frame.</summary>
        private bool Ending(AnimatorStateInfo state)
        {
            float blendFraction = state.length > 0.01f ? _blendSeconds / state.length : 0f;
            return state.normalizedTime >= 1f - blendFraction;
        }

        /// <summary>The original single-layer behaviour, kept for a controller built before the
        /// masked layer existed. It cross-fades the whole body, legs included.</summary>
        private void UpdateFullBody()
        {
            // Mid-blend the reported state is still the one being left; let the transition land
            // before reading anything from it.
            if (_animator.IsInTransition(0)) return;

            var state = _animator.GetCurrentAnimatorStateInfo(0);

            if (state.shortNameHash == _accentHash)
            {
                // Start the return early enough that the cross-fade covers the accent's tail
                // instead of holding its last frame.
                float blendFraction = state.length > 0.01f ? _blendSeconds / state.length : 0f;
                if (state.normalizedTime >= 1f - blendFraction)
                {
                    _animator.CrossFadeInFixedTime(_idleHash, _blendSeconds);
                    _loopsSeen = 0;
                    _lastIdleTime = 0f;
                }
                return;
            }

            // Anything else owns the body right now (a victory, a duel pose) — stay out of its way.
            if (state.shortNameHash != _idleHash) return;

            float t = state.normalizedTime % 1f;
            if (t < _lastIdleTime) _loopsSeen++;   // normalizedTime wrapped: one loop done
            _lastIdleTime = t;

            if (_loopsSeen >= _loopsBetweenAccents)
                _animator.CrossFadeInFixedTime(_accentHash, _blendSeconds);
        }
    }
}
